version: '3.8'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariaDB
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb_storage:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306"
  nginx:
    container_name: nginx
    volumes:
      - wordpress_storage:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    volumes:
      - wordpress_storage:/var/www/wordpress
    env_file: .env
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
        - mariadb
    restart: on-failure
    expose:
      - "9000"
volumes:
  wordpress_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/wordpress'
  mariadb_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/mariadb'
networks:
  inception: